settings:
  api:
    key: "your_api_key"
    url: "https://api.example.com"
  database:
    url: "postgresql://user:password@localhost/dbname"
    pool_size: 10
###
disease_name: Lung cancer
drug_name:
  - 大枣
  - 人参
  - 陈皮
results_dir: results
